project:
  type: website
  output-dir: docs
website:
  title: "Alexandre Daby-Seesaram"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: talks.qmd
        text: Talks
      - href: add_resources.qmd
        text: Resources
      - href: TA.qmd
        text: Teaching
      - href: education.qmd
        text: Education
      - text: CV
        href: Resources/Documents/CV.pdf
        target: _blank


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    include-after-body:
      text: |
        <script type="application/javascript" src="custom_hal.js"></script>



