project:
  type: website
  output-dir: docs
website:
  title: "Alexandre Daby-Seesaram"
  description: "Alexandre Daby-Seesaram, PHD, personal webpage"
  site-url: https://alexandredabyseesaram.github.io/
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: talks.qmd
        text: Talks
      - href: news.qmd
        text: News
      - href: add_resources.qmd
        text: Resources
      - href: TA.qmd
        text: Teaching
      - href: education.qmd
        text: Education
      - text: CV
        href: Resources/Documents/CV.pdf
        target: _blank
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Conference incoming** - We'll be [presenting our work](https://alexandredabyseesaram.github.io/talks.html) at the incoming [VPH2024 in Stuttgart](https://vph-conference.org/) "
    type: light
    position: below-navbar

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    include-after-body:
      text: |
        <script type="application/javascript" src="custom_hal.js"></script>



