---
title: Talks (selection)
format:
  html:
    page-layout: full
---

:::: {style='margin-top: 3em;'}
::::

## {{< iconify fa-solid:bullhorn >}} &nbsp; Incoming talks

:::: {style='margin-top: 3em;'}
::::


::::: {.talk-card}
### DTE & AICOMAS 2025 ([website](https://dte_aicomas_2025.iacm.info/me/contributions))
*Paris, France, 17th - 21st of February 2025*

**Title:** Finite Element Neural Network Interpolation: Hybridisation with the Proper Generalised Decomposition for Surrogate Modelling 

**Authors:** [A. Daby-Seesaram](index.qmd), [K. Škardová](https://m3disim.saclay.inria.fr/people/katerina-skardova), [M. Genet](https://mgenet.github.io/)

:::::


## {{< iconify fa6-solid:clock-rotate-left >}} &nbsp; Past talks

### &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Invited Speaker

:::: {style='margin-top: 2em;'}
::::

<!-- +-----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| Austrian Academy of Sciences,                                         |  Linz, Austria, 21st-28th of October 2024                                           |                                
|[RICAM](https://www.oeaw.ac.at/de/ricam/research/groups/group-egger)   |                                                                                     |
+=======================================================================+=====================================================================================+
| Authors                                                               | <a href="index.qmd">A. Daby-seesaram<a>,                                            |
|                                                                       | <a href="https://m3disim.saclay.inria.fr/people/katerina-skardova/">K. Škardová<a>, |
|                                                                       | <a href="https://mgenet.github.io/">M. Genet<a>                                     |
+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| Link                                                                  | [Slides](Resources/Documents/Presentations/RICAM/TODO.html),                        |
|                                                                       |                                [Code](https://pypi.org/project/NeuROM-Py/)          |
+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------+
 -->

::: {.talk-card}
### RICAM - Austrian Academy of Sciences Seminar ([website](https://www.oeaw.ac.at/ricam/))
*Linz, Austria, 21st-28th of October*

**Authors:** [A. Daby-Seesaram](index.qmd), [K. Škardová](https://m3disim.saclay.inria.fr/people/katerina-skardova), [M. Genet](https://mgenet.github.io/)

:::: {.columns}

::: {.column width="80pt"}

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="Slides"></iconify-icon> Slides](Resources/Documents/Presentations/RICAM/TODO.html){.button target="_blank"}

:::

:::

::: {.column width="80pt"}

::: {.button}

[<iconify-icon icon="fa-solid:code" aria-label="Code"></iconify-icon> Code](https://pypi.org/project/NeuROM-Py/){.button target="_blank"}

:::

:::

::::

:::


### &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Conferences
:::: {style='margin-top: 2em;'}
::::

<!-- +----------------------------------------+-------------------------------------------------------------------------------------+
| Virtual Physiological Human (VPH) 2024 | Stuttgart, Germany, 3rd - 6th of September 2024                                     |
+========================================+=====================================================================================+
| Title                                  | Hybridising standard ROM methods with interpretable sparse neural networks          |
|                                        |for real-time patient specific lung simulations                                      |
+----------------------------------------+-------------------------------------------------------------------------------------+
| Authors                                | <a href="index.qmd">A. Daby-seesaram<a>,                                            |
|                                        | <a href="https://m3disim.saclay.inria.fr/people/katerina-skardova/">K. Škardová<a>, |
|                                        | <a href="https://mgenet.github.io/">M. Genet<a>                                     |
+----------------------------------------+-------------------------------------------------------------------------------------+
| Link                                   | [Slides](Resources/Documents/Presentations/VPH2024/TODO.html),                      |
|                                        |                                [Code](https://pypi.org/project/NeuROM-Py/)          |
+----------------------------------------+-------------------------------------------------------------------------------------+ -->


::: {.talk-card}
### Virtual Physiological Human (VPH) 2024 ([website](https://vph-conference.org/))
*Stuttgart, Germany, 3rd - 6th of September 2024*

**Title:** Hybridising standard ROM methods with interpretable sparse neural networks for real-time patient specific lung simulations

**Authors:** [A. Daby-Seesaram](index.qmd), [K. Škardová](https://m3disim.saclay.inria.fr/people/katerina-skardova), [M. Genet](https://mgenet.github.io/)

:::: {.columns}

::: {.column width="80pt"}

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="Slides"></iconify-icon> Slides](Resources/Documents/Presentations/RICAM/TODO.html){.button target="_blank"}

:::

:::

::: {.column width="80pt"}

::: {.button}

[<iconify-icon icon="fa-solid:code" aria-label="Code"></iconify-icon> Code](https://pypi.org/project/NeuROM-Py/){.button target="_blank"}

:::

:::

::::

:::